spring:

  #数据源配置
  datasource:
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/CEEVR?useSSL=false&useUnicode=yes&characterEncoding=UTF8
    #url:jdbc:mysql://localhost:3306/powerteam?useSSL=false&useUnicode=yes&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    #连接数据库用户名
    username: root
    #连接数据库密码
    password: 122333zwz